const merchantsApi = [
  {
    id: '1',
    firstname: 'Dawid',
    lastname: 'Piwko',
    avatarUrl: 'https://api.adorable.io/avatars/100/1',
    email: 'dpiwko@gmail.com',
    phone: '789123456',
    hasPremium: true,
    bids: [
      {
        id: '1',
        carTitle: 'Audi A3',
        amount: 8,
        created: '2016',
      },
      {
        id: '2',
        carTitle: 'Volkswagen Golf 3',
        amount: 20,
        created: '2000',
      },
      {
        id: '3',
        carTitle: 'Nissan GTR',
        amount: 2,
        created: '2017',
      },
      {
        id: '4',
        carTitle: 'Audi RS5',
        amount: 4,
        created: '2020',
      },
    ],
  },
  {
    id: '2',
    firstname: 'Justyna',
    lastname: 'Królowa',
    avatarUrl: 'https://api.adorable.io/avatars/100/2',
    email: 'krolewna@gmail.com',
    phone: '789123123',
    hasPremium: true,
    bids: [],
  },
  {
    id: '3',
    firstname: 'Marcin',
    lastname: 'Brat',
    avatarUrl: 'https://api.adorable.io/avatars/100/3',
    email: 'marcin97@o2.pl',
    phone: '787123678',
    hasPremium: true,
    bids: [],
  },
  {
    id: '4',
    firstname: 'Anna',
    lastname: 'Jantar',
    avatarUrl: 'https://api.adorable.io/avatars/100/4',
    email: 'annajantar@onet.pl',
    phone: '678123678',
    hasPremium: false,
    bids: [],
  },
  {
    id: '5',
    firstname: 'Leszek',
    lastname: 'Nosacz',
    avatarUrl: 'https://api.adorable.io/avatars/100/5',
    email: 'l.nosacz00@interia.pl',
    phone: '678006791',
    hasPremium: false,
    bids: [
      {
        id: '1',
        carTitle: 'Opel Corsa',
        amount: 123,
        created: '1999',
      },
      {
        id: '2',
        carTitle: 'Daewoo Tico',
        amount: 543,
        created: '1994',
      },
    ],
  },
  {
    id: '6',
    firstname: 'Wojciech',
    lastname: 'Zawada',
    avatarUrl: 'https://api.adorable.io/avatars/100/6',
    email: 'wojtek.zawada@gmail.com',
    phone: '542876879',
    hasPremium: false,
    bids: [],
  },
  {
    id: '7',
    firstname: 'Jacek',
    lastname: 'Placek',
    avatarUrl: 'https://api.adorable.io/avatars/100/7',
    email: 'placek@poczta.onet.com',
    phone: '789789789',
    hasPremium: false,
    bids: [],
  },
  {
    id: '8',
    firstname: 'Iwona',
    lastname: 'Browar',
    avatarUrl: 'https://api.adorable.io/avatars/100/8',
    email: 'iwciaaa88@poczta.wp.pl',
    phone: '678123789',
    hasPremium: false,
    bids: [],
  },
  {
    id: '9',
    firstname: 'Michał',
    lastname: 'Banan',
    avatarUrl: 'https://api.adorable.io/avatars/100/9',
    email: 'bananowy@gmail.com',
    phone: '567213788',
    hasPremium: true,
    bids: [
      {
        id: '1',
        carTitle: 'Ford Raptor',
        amount: 3,
        created: '2014',
      },
      {
        id: '2',
        carTitle: 'Ford GT',
        amount: 1,
        created: '2000',
      },
    ],
  },
  {
    id: '10',
    firstname: 'Oskar',
    lastname: 'Łeb',
    avatarUrl: 'https://api.adorable.io/avatars/100/10',
    email: 'oskarinio@gmail.com',
    phone: '987786123',
    hasPremium: true,
    bids: [],
  },
]

export default merchantsApi
