/**
 * Mutations put in one place to be easier to find and remove
 *
 * INFO: Try to keep alphabetical order
 */

// MERCHANT
export const ADD_MERCHANT = 'ADD_MERCHANT'
export const ADD_MERCHANT_FAILURE = 'ADD_MERCHANT_FAILURE'
export const ADD_MERCHANT_SUCCESS = 'ADD_MERCHANT_SUCCESS'

export const DELETE_MERCHANT = 'DELETE_MERCHANT'
export const DELETE_MERCHANT_FAILURE = 'DELETE_MERCHANT_FAILURE'
export const DELETE_MERCHANT_SUCCESS = 'DELETE_MERCHANT_SUCCESS'

export const GET_MERCHANT_BY_ID = 'GET_MERCHANT_BY_ID'
export const GET_MERCHANT_BY_ID_FAILURE = 'GET_MERCHANT_BY_ID_FAILURE'
export const GET_MERCHANT_BY_ID_SUCCESS = 'GET_MERCHANT_BY_ID_SUCCESS'

export const GET_MERCHANTS = 'GET_MERCHANTS'
export const GET_MERCHANTS_FAILURE = 'GET_MERCHANTS_FAILURE'
export const GET_MERCHANTS_SUCCESS = 'GET_MERCHANTS_SUCCESS'

export const EDIT_MERCHANT = 'EDIT_MERCHANT'
export const EDIT_MERCHANT_FAILURE = 'EDIT_MERCHANT_FAILURE'
export const EDIT_MERCHANT_SUCCESS = 'EDIT_MERCHANT_SUCCESS'
